<?php
include("../includes/config.php");
include("../includes/TOTP.php");
// session_start(); // Already called in config.php

if (!isset($_SESSION['temp_user_id'])) {
    header("Location: index.php");
    exit();
}

$user_id = $_SESSION['temp_user_id'];

// Fetch user status and secret
$stmt = $con->prepare("SELECT id, user_name, role, two_factor_secret, two_factor_enabled FROM admin WHERE id = ?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$user = $result->fetch_assoc();

// If no secret exists, generate one now
if (empty($user['two_factor_secret'])) {
    $new_secret = TOTP::generateSecret();
    $up_stmt = $con->prepare("UPDATE admin SET two_factor_secret = ? WHERE id = ?");
    $up_stmt->bind_param("si", $new_secret, $user_id);
    $up_stmt->execute();
    $user['two_factor_secret'] = $new_secret;
}

$error = '';
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $code = isset($_POST['code']) ? trim($_POST['code']) : '';

    if (TOTP::verifyCode($user['two_factor_secret'], $code)) {
        // Success
        
        // If it was the first time setup, mark as enabled
        if (!$user['two_factor_enabled']) {
            $enable_stmt = $con->prepare("UPDATE admin SET two_factor_enabled = 1 WHERE id = ?");
            $enable_stmt->bind_param("i", $user_id);
            $enable_stmt->execute();
        }

        $_SESSION['user_name'] = $user['user_name'];
        $_SESSION['admin_id'] = $user_id;
        $_SESSION['role'] = $user['role'];
        $_SESSION['last_activity'] = time();
        
        unset($_SESSION['temp_user_id']);
        unset($_SESSION['temp_user_name']);
        unset($_SESSION['temp_role']);
        
        session_regenerate_id(true);
        header("Location: dashboard.php");
        exit();
    } else {
        $error = "Invalid 2FA code. Please try again.";
    }
}

$qr_code_url = TOTP::getQRCodeGoogleUrl($user['user_name'], $user['two_factor_secret'], 'ScansWorld');
?>
<!doctype html>
<html lang="en">
<head>
    <title>2FA Verification | Scans World</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="assets/css/style.css" />
    <style>
        .container { display: flex; justify-content: center; align-items: center; min-height: 100vh; padding: 20px; }
        .box { width: 100%; max-width: 450px; padding: 30px; border: 1px solid #ddd; border-radius: 12px; box-shadow: 0 8px 16px rgba(0,0,0,0.1); background: #fff; }
        .form-group { margin-bottom: 20px; }
        .form-control { width: 100%; padding: 12px; border: 1px solid #ccc; border-radius: 6px; text-align: center; font-size: 1.5rem; letter-spacing: 5px; }
        .btn-primary { width: 100%; padding: 12px; background-color: #007bff; border: none; color: white; border-radius: 6px; cursor: pointer; font-weight: 600; }
        .error { color: #dc3545; margin-bottom: 15px; text-align: center; background: #f8d7da; padding: 10px; border-radius: 4px; }
        .qr-section { text-align: center; margin-bottom: 25px; border-bottom: 1px solid #eee; padding-bottom: 20px; }
        .qr-section img { max-width: 180px; margin-bottom: 15px; }
        .setup-steps { font-size: 0.9rem; color: #555; text-align: left; margin-bottom: 15px; }
        .setup-steps ol { padding-left: 20px; }
    </style>
</head>
<body>
<div class="container">
    <div class="box">
        <h2 style="text-align: center; margin-bottom: 20px;">2FA Verification</h2>
        
        <?php if (!$user['two_factor_enabled']): ?>
            <div class="qr-section">
                <h5>Setup Two-Factor Authentication</h5>
                <p>Scan this QR code with Google Authenticator or Authy to secure your account.</p>
                <img src="<?php echo $qr_code_url; ?>" alt="QR Code">
                <p><strong>Secret Key:</strong> <code style="background: #f4f4f4; padding: 2px 5px;"><?php echo $user['two_factor_secret']; ?></code></p>
            </div>
            <div class="setup-steps">
                <ol>
                    <li>Open your authenticator app.</li>
                    <li>Scan the QR code above or enter the secret key.</li>
                    <li>Enter the 6-digit code generated by the app below.</li>
                </ol>
            </div>
        <?php else: ?>
            <p style="text-align: center;">Enter the 6-digit code from your authenticator app to continue.</p>
        <?php endif; ?>

        <?php if ($error): ?>
            <div class="error"><?php echo $error; ?></div>
        <?php endif; ?>

        <form method="POST">
            <div class="form-group">
                <input type="text" name="code" class="form-control" maxlength="6" pattern="\d{6}" placeholder="000000" required autofocus autocomplete="off">
            </div>
            <button type="submit" class="btn-primary">Verify & Login</button>
            <div style="text-align: center; margin-top: 20px;">
                <a href="index.php" style="color: #666; text-decoration: none;">&larr; Back to Login</a>
            </div>
        </form>
    </div>
</div>
</body>
</html>
